<a href="https://colab.research.google.com/github/OlgaNezh/PyTorch/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22HW_1_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import numpy as np

In [ ]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [3]:
x = torch.randn(3, 4, 5).type(torch.float32)
print("x :\n%s\n" % x)

x :
tensor([[[-0.2288,  0.2597,  1.7912,  2.5227, -0.1284],
         [ 1.0030, -2.3438, -1.7318, -2.2063, -1.1461],
         [ 1.1593,  1.3143, -1.5298,  1.1142,  0.7677],
         [-0.5319, -0.2576,  1.6123, -0.4795,  2.0111]],

        [[ 0.8715, -0.3775,  1.4942, -0.8914,  1.3602],
         [ 0.5261, -0.0726, -0.8665, -0.1063, -0.0122],
         [ 0.2461,  1.7115, -0.6016, -1.0062, -0.5455],
         [-0.9896, -0.4684, -0.1904, -1.0930, -0.5548]],

        [[-0.0214, -0.4220,  0.3018,  0.6125, -0.0145],
         [ 1.8669,  0.9752,  0.3378, -0.5072,  0.8104],
         [-0.3088,  0.7933,  1.7220,  0.6505, -1.0211],
         [-0.4256, -0.3852,  0.3960, -0.4415,  0.2351]]])



In [ ]:
# 2. Выведите его форму (shape)

In [5]:
print("x форма: %s\n" % (x.shape,))


x форма: torch.Size([3, 4, 5])



In [ ]:
# 3. Приведите его к форме 6х10

In [6]:
x = torch.reshape(x, [6, 10])
x, x.shape

(tensor([[-0.2288,  0.2597,  1.7912,  2.5227, -0.1284,  1.0030, -2.3438, -1.7318,
          -2.2063, -1.1461],
         [ 1.1593,  1.3143, -1.5298,  1.1142,  0.7677, -0.5319, -0.2576,  1.6123,
          -0.4795,  2.0111],
         [ 0.8715, -0.3775,  1.4942, -0.8914,  1.3602,  0.5261, -0.0726, -0.8665,
          -0.1063, -0.0122],
         [ 0.2461,  1.7115, -0.6016, -1.0062, -0.5455, -0.9896, -0.4684, -0.1904,
          -1.0930, -0.5548],
         [-0.0214, -0.4220,  0.3018,  0.6125, -0.0145,  1.8669,  0.9752,  0.3378,
          -0.5072,  0.8104],
         [-0.3088,  0.7933,  1.7220,  0.6505, -1.0211, -0.4256, -0.3852,  0.3960,
          -0.4415,  0.2351]]), torch.Size([6, 10]))

In [ ]:
# 4. Создайте случайный IntTensor размера 10

In [10]:
a = torch.IntTensor(10)
a.type(), a

('torch.IntTensor',
 tensor([ 118436160,          0,         24,          0,         -1,   16843009,
         1668444020, 1767059048, 1529374074,    2710833], dtype=torch.int32))

In [ ]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [11]:
x * a

tensor([[-2.7103e+07,  0.0000e+00,  4.2989e+01,  0.0000e+00,  1.2843e-01,
          1.6893e+07, -3.9105e+09, -3.0602e+09, -3.3742e+09, -3.1069e+06],
        [ 1.3730e+08,  0.0000e+00, -3.6716e+01,  0.0000e+00, -7.6772e-01,
         -8.9580e+06, -4.2984e+08,  2.8490e+09, -7.3331e+08,  5.4518e+06],
        [ 1.0322e+08, -0.0000e+00,  3.5861e+01, -0.0000e+00, -1.3602e+00,
          8.8617e+06, -1.2111e+08, -1.5312e+09, -1.6252e+08, -3.2939e+04],
        [ 2.9144e+07,  0.0000e+00, -1.4438e+01, -0.0000e+00,  5.4547e-01,
         -1.6668e+07, -7.8142e+08, -3.3650e+08, -1.6717e+09, -1.5040e+06],
        [-2.5358e+06, -0.0000e+00,  7.2430e+00,  0.0000e+00,  1.4467e-02,
          3.1444e+07,  1.6271e+09,  5.9691e+08, -7.7574e+08,  2.1968e+06],
        [-3.6579e+07,  0.0000e+00,  4.1328e+01,  0.0000e+00,  1.0211e+00,
         -7.1692e+06, -6.4266e+08,  6.9974e+08, -6.7517e+08,  6.3743e+05]])

In [ ]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [12]:
x @ x.T

tensor([[ 2.5388e+01, -3.9208e+00,  2.4024e+00,  3.2471e-01,  1.1748e+00,
          5.6277e+00],
        [-3.9208e+00,  1.4466e+01, -3.3523e+00,  1.6633e+00,  8.0363e-01,
         -3.6033e-01],
        [ 2.4024e+00, -3.3523e+00,  6.8237e+00, -1.3744e+00,  6.8878e-01,
         -4.5951e-01],
        [ 3.2471e-01,  1.6633e+00, -1.3744e+00,  7.3991e+00, -3.7812e+00,
          1.0267e+00],
        [ 1.1748e+00,  8.0363e-01,  6.8878e-01, -3.7812e+00,  6.1094e+00,
         -1.7366e-02],
        [ 5.6277e+00, -3.6033e-01, -4.5951e-01,  1.0267e+00, -1.7366e-02,
          5.8923e+00]])

In [ ]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [14]:
from torch.autograd import Variable

In [15]:
x = Variable(torch.Tensor([1]), requires_grad = True) 
z = Variable(torch.Tensor([0.5]), requires_grad = True) 
t = Variable(torch.Tensor([2]), requires_grad = True) 

y = x**3 + z - 75*t
print('Значение функции y в точке:', y.item())

y.backward() 

print('Производная функции y по x в точке: ', x.grad.item())
print('Производная функции y по z в точке: ', z.grad.item())
print('Производная функции y по t в точке: ', t.grad.item()) 

Значение функции y в точке: -148.5
Производная функции y по x в точке:  3.0
Производная функции y по z в точке:  1.0
Производная функции y по t в точке:  -75.0


In [ ]:
# 8. Создайте единичный тензор размера 5x6

In [16]:
b = torch.ones([5, 6])
b, b.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]), torch.Size([5, 6]))

In [ ]:
# 9. Переведите его в формат numpy

In [17]:
b = b.numpy()
b

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)